### ISSUE TITLE
Problem with setting VectorDrawables via setCompoundDrawables on a Button

### ISSUE THREAD

**Issue by zaichang** [wnafee/vector-compat#22]
I'm trying to use the vector drawables on a button, specifically the drawableLeft and drawableRight attributes. This is done in code like this:

```
    Drawable drawable = ResourcesCompat.getDrawable(context, R.drawable.vector_icon);
    button.setCompoundDrawables(drawable, null, null, null);
```

However, if I put the same drawable inside an ImageView via setDrawable, then it works:

```
    imageView.setImageDrawable(drawable);
```

This seems to be happening on 5.0, 4.4 and 4.3. And interestingly the drawable on the button would actually draw if I have an image view also visible in the view using the same drawable.

**Comment by wnafee** [comment]
Can you describe what exact problem you're seeing?
Also, can you try testing without the vector-compat library on 5.0? The reason is that the current implementation does a fallback on the default 5.0 implementation if you're on lollipop. So the fact that you cannot make it work on 5.0 makes me think this could be a general VectorDrawable problem.

Please test and update us here.

**Comment by zaichang** [comment]
If I just set the Button's using setCompoundDrawable in code as mentioned above, it doesn't draw on screen as if I didn't set a drawable at all. This problem occurs in both L and 4.4.

Eventually while searching on the matter I found that instead of using setCompoundDrawables, I should instead use setCompoundDrawablesWithIntrinsicBounds for the desired results:
http://stackoverflow.com/questions/15709648/textview-setcompounddrawables-dont-change-or-show

The VectorDrawable is now drawn so I'm closing the issue, sorry for the red herring.
