### ISSUE TITLE
Failed to load animators on android 6.0

### ISSUE THREAD

**Issue by marianpavel** [wnafee/vector-compat#29]
I receive this error on Nexus 7 2013 with my project using vector-compat:

Failed to load animators. Either the AnimatedVectorDrawable must be created using a Resources object or applyTheme() must be called with a non-null Theme object.

The button is not functional, can't be clicked.

Is there a way how to fix this ? Working good on L devices and Kitkat.

**Comment by MinceMan** [comment]
I've ran into this before too. Is there a way we can force Marshmallow to use the compat drawables?

**Comment by MinceMan** [comment]
I've ran into this as well. It has to do with a system level bug in which they're not correctly reusing a drawable from the drawable cache. What you can do is to programmatically inflate the compat drawables instead of the system drawables.

``` java

        AnimatedVectorDrawable startDrawable = AnimatedVectorDrawable.getDrawable(playButton.getContext(), R.drawable.vector_play_pause);
        AnimatedVectorDrawable endDrawable = AnimatedVectorDrawable.getDrawable(playButton.getContext(), R.drawable.vector_pause_play);

        playButton.setStartDrawable(startDrawable);
        playButton.setEndDrawable(endDrawable);
```

**Comment by marianpavel** [comment]
You saved me.

**Comment by DenisMondon** [comment]
Hi!

I'm using ResourcesCompat.getDrawable() but I have the same error:
`Failed to load animators. Either the AnimatedVectorDrawable must be created using a Resources object or applyTheme() must be called with a non-null Theme object.`

What can I do?
(Android 6.0.1)

Thanks.

EDIT:
I found the problem.
It was because I had the attribute android:tint="#FFFFFF" in my FloatingActionButton.
When I removed it, it worked immediately.
